
# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml

# Build version format
version: "{build}"

clone_depth: 10
# Fix line endings on Windows
init:
  - git config --global core.autocrlf true

# What combinations to test
environment:
  matrix:
    - nodejs_version: 0.10
    - nodejs_version: 0.12
    - nodejs_version: 1

install:
  - ps: >-
    #Make sure 7za is installed
    choco install 7zip.commandline
    # Create mongodb and data directory
    md $env:temp\mongo\data
    # Go to mongodb dir
    Push-Location $env:temp\mongo
    # Download zipped mongodb binaries to mongodbdir
    Invoke-WebRequest https://fastdl.mongodb.org/win32/mongodb-win32-x86_64-2008plus-2.6.5.zip -OutFile mongodb.zip
    # Extract mongodb zip
    cmd /c 7za e mongodb.zip
    # Install mongodb as a windows service
    cmd /c $env:temp\mongo\mongod.exe --logpath=$env:temp\mongo\log --dbpath=$env:temp\mongo\data\ --smallfiles --install
    # Sleep as a hack to fix an issue where the service sometimes does not finish installing quickly enough
    Start-Sleep -Seconds 5
    # Start mongodb service
    net start mongodb
    # Return to last location, to run the build
    Pop-Location
    Write-Host
    Write-Host "monogdb installation complete"
  - ps: Install-Product node $env:nodejs_version
  - npm install -g grunt-cli
  - npm install

build: off

test_script:
  # Output useful info for debugging.
  - node --version && npm --version
  # We test multiple Windows shells because of prior stdout buffering issues
  # filed against Grunt. https://github.com/joyent/node/issues/3584
  - ps: "npm test # PowerShell" # Pass comment to PS for easier debugging
  - cmd: npm test

matrix:
  fast_finish: true

cache:
  - C:\Users\appveyor\AppData\Roaming\npm\node_modules -> package.json  # global npm modules
  - C:\Users\appveyor\AppData\Roaming\npm-cache -> package.json         # npm cache

